global:
scrape_interval:     15s 
external_labels:
monitor: 'codelab-monitor'
scrape_configs:
- job_name: 'prometheus'    
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
      - targets: ['10.0.1.3:9100']
      - targets: ['localhost:9100']
