global:
  scrape_interval: 1m
  external_labels:
    monitor: 'node'
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]
    - targets: ["localhost:9100"]
    - targets: ["10.0.1.3:9100"]
